
flights = [
    {
        "flight_number": "SK142",
        "destination": "London",
        "departure_time": "14:30",
        "gate": "B4",
        "passengers": 132,
        "capacity": 180,
        "delay": 25,
        "cancelled": False,
    },
    {
        "flight_number": "LH231",
        "destination": "Berlin",
        "departure_time": "15:00",
        "gate": "A2",
        "passengers": 96,
        "capacity": 150,
        "delay": 0,
        "cancelled": False,
    },
    {
        "flight_number": "BA442",
        "destination": "Manchester",
        "departure_time": "15:20",
        "gate": "C1",
        "passengers": 88,
        "capacity": 140,
        "delay": 75,
        "cancelled": False,
    },
    {
        "flight_number": "AF118",
        "destination": "Paris",
        "departure_time": "16:10",
        "gate": "A1",
        "passengers": 70,
        "capacity": 120,
        "delay": 10,
        "cancelled": False,
    },
    {
        "flight_number": "EK301",
        "destination": "Dubai",
        "departure_time": "17:45",
        "gate": "B2",
        "passengers": 150,
        "capacity": 180,
        "delay": 0,
        "cancelled": False,
    },
    {
        "flight_number": "QR110",
        "destination": "Doha",
        "departure_time": "18:15",
        "gate": "C3",
        "passengers": 42,
        "capacity": 130,
        "delay": 30,
        "cancelled": False,
    },
    {
        "flight_number": "LX900",
        "destination": "Zurich",
        "departure_time": "19:00",
        "gate": "A4",
        "passengers": 110,
        "capacity": 170,
        "delay": 5,
        "cancelled": False,
    },
    {
        "flight_number": "TG440",
        "destination": "Bangkok",
        "departure_time": "19:50",
        "gate": "B1",
        "passengers": 182,
        "capacity": 200,
        "delay": 0,
        "cancelled": False,
    },
    {
        "flight_number": "AZ210",
        "destination": "Rome",
        "departure_time": "20:40",
        "gate": "C4",
        "passengers": 61,
        "capacity": 140,
        "delay": 45,
        "cancelled": False,
    },
    {
        "flight_number": "KL560",
        "destination": "Amsterdam",
        "departure_time": "21:05",
        "gate": "B3",
        "passengers": 134,
        "capacity": 180,
        "delay": 0,
        "cancelled": False,
    },
]

for flight in flights:
    print(flight)
